// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwmjx75nzPDQKrn4qsVItkNGv3QV95Kx4',
    appId: '1:326749484112:web:1c024ac15c7618f902cd55',
    messagingSenderId: '326749484112',
    projectId: 'galaxymob-65bae',
    authDomain: 'galaxymob-65bae.firebaseapp.com',
    storageBucket: 'galaxymob-65bae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXwlTG_tCtIIq7ljNY_6Ssyi7pLXm6Lw8',
    appId: '1:326749484112:android:9b922969300b010802cd55',
    messagingSenderId: '326749484112',
    projectId: 'galaxymob-65bae',
    storageBucket: 'galaxymob-65bae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHJckn_v3Ewinbe2c1JbHad338fUEjsAI',
    appId: '1:326749484112:ios:76a03e6f4555206b02cd55',
    messagingSenderId: '326749484112',
    projectId: 'galaxymob-65bae',
    storageBucket: 'galaxymob-65bae.firebasestorage.app',
    iosClientId: '326749484112-crblc8vl60foe1r2ggel9bdc5tm3edpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.galaxymob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHJckn_v3Ewinbe2c1JbHad338fUEjsAI',
    appId: '1:326749484112:ios:76a03e6f4555206b02cd55',
    messagingSenderId: '326749484112',
    projectId: 'galaxymob-65bae',
    storageBucket: 'galaxymob-65bae.firebasestorage.app',
    iosClientId: '326749484112-crblc8vl60foe1r2ggel9bdc5tm3edpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.galaxymob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwmjx75nzPDQKrn4qsVItkNGv3QV95Kx4',
    appId: '1:326749484112:web:b75ba881652f354102cd55',
    messagingSenderId: '326749484112',
    projectId: 'galaxymob-65bae',
    authDomain: 'galaxymob-65bae.firebaseapp.com',
    storageBucket: 'galaxymob-65bae.firebasestorage.app',
  );
}
